import type { Track } from "@/context/MusicPlayerContext"

export const sampleTracks: Track[] = [
  {
    id: "1",
    title: "Formation",
    artist: "Beyoncé",
    albumArt: "/woman-on-police-car.png",
    audioSrc: "https://audio-samples.github.io/samples/mp3/sample1.mp3",
    duration: 236,
    platform: "spotify",
    externalUrl: "https://open.spotify.com/track/6g0Orsxv6glTJCt4cHsRsQ",
  },
  {
    id: "2",
    title: "Kill Bill",
    artist: "SZA",
    albumArt: "/revenge-fantasy.png",
    audioSrc: "https://audio-samples.github.io/samples/mp3/sample2.mp3",
    duration: 153,
    platform: "spotify",
    externalUrl: "https://open.spotify.com/track/1Qrg8KqiBpW07V7PNxwwwL",
  },
  {
    id: "3",
    title: "Make Me Feel",
    artist: "Janelle Monáe",
    albumArt: "/Abstract Expression of "Make Me Feel".png",
    audioSrc: "https://audio-samples.github.io/samples/mp3/sample3.mp3",
    duration: 194,
    platform: "apple",
    externalUrl: "https://music.apple.com/us/album/make-me-feel/1440818584?i=1440818730",
  },
  {
    id: "4",
    title: "Cranes in the Sky",
    artist: "Solange",
    albumArt: "/Abstract Cranes.png",
    audioSrc: "https://audio-samples.github.io/samples/mp3/sample4.mp3",
    duration: 261,
    platform: "youtube",
    externalUrl: "https://www.youtube.com/watch?v=S0qrinhNnOM",
  },
  {
    id: "5",
    title: "Golden",
    artist: "Jill Scott",
    albumArt: "/golden-woman-portrait.png",
    audioSrc: "https://audio-samples.github.io/samples/mp3/sample5.mp3",
    duration: 218,
    platform: "spotify",
    externalUrl: "https://open.spotify.com/track/1Qrg8KqiBpW07V7PNxwwwL",
  },
  {
    id: "6",
    title: "On & On",
    artist: "Erykah Badu",
    albumArt: "/placeholder.svg?height=400&width=400&query=Erykah+Badu+On+and+On+album+cover",
    audioSrc: "https://audio-samples.github.io/samples/mp3/sample6.mp3",
    duration: 228,
    platform: "apple",
    externalUrl: "https://music.apple.com/us/album/on-on/1440762235?i=1440762572",
  },
]
