# Configuration for Shopify App
name = "midnight-magnolia-vizify"
client_id = "YOUR_SHOPIFY_CLIENT_ID"
application_url = "https://midnight-magnolia-vizify.vercel.app"
embedded = true

[auth]
redirect_urls = [
  "https://midnight-magnolia-vizify.vercel.app/api/auth/callback",
  "http://localhost:3000/api/auth/callback"
]

[webhooks]
api_version = "2023-10"

[pos]
embedded = false

[build]
dev_store_url = "midnight-magnolia.myshopify.com"